### ISSUE TITLE
Example Beancount file with usage pattern

### ISSUE THREAD

**Issue by Zburatorul** [polarmutex/fava-envelope#17]
After reading the Beancount mailing list, the Fava Issues post, and [this post](https://frdmtoplay.com/envelope-budgeting-with-ledger/) about envelope budgeting for ledger I gather there are many opinions on how envelope budgeting should be done on top of a double-entry bookkeeping system.

@bryall, in order to understand your vision for this extension and its correct usage it would be very helpful to have a basic example Beancount journal with some transactions in it, and perhaps a few screenshots with some brief commentary.

**Comment by bryall** [comment]
I agree, I have been focusing on some other projects and will add those as soon as I can

**Comment by Zburatorul** [comment]
One situation I don't understand how to handle is the following: I want to see that I'm investing 100 USD a month. The transactions might look like:
```
2020-08-01 * "Investing"
 Assets:Bank                  -100 USD
 Assets:Investing:Cash   100 USD

2020-08-01 * "Buy investment vehicle"
 Assets:Investing:Cash    -100 USD
 Expenses:Investing              1 USD
 Assets:Investing:TICKER    10 TICKER {99 USD}
```

So really a deposit into `Assets:Investing:Cash` should count towards the monthly `100 USD` "budget". The problem is that the USD comes and leaves the account, so it will always look like nothing happened.

**Comment by bryall** [comment]
I have added an example file to the repo, with a link to repl.it to see it in action.

with your example, if you set the "Assets:Bank" as the only budget account , the second journal entry will not be processed. then you can map the  100 USD to a budget envelope.

All the design decisions have been for me so far, but I am very open to change and discuss alternatives to make this better, let me know if you have any other questions
