### ISSUE TITLE
Support fava v1.19

### ISSUE THREAD

**Issue by JonBoyleCoding** [polarmutex/fava-envelope#20]
I'm testing this out, but all I get is a display showing lists of object types:

![image](https://user-images.githubusercontent.com/630329/108931079-f5463100-763e-11eb-96d2-46352510e82a.png)

Example beancount file below:

```
option "title" "Budget Testing Ledger"
option "operating_currency" "GBP"

2000-01-01 custom "fava-extension" "fava_envelope" "{}"

2020-08-01 custom "envelope" "start date" "2020-08"
2020-08-01 custom "envelope" "budget account" "Assets:GBP"

2000-01-01 open Equity:Opening-Balances
2000-01-01 open Assets:GBP:Current
2020-01-01 open Expenses:Learning                               GBP


2020-08-14 pad Assets:GBP:Current Equity:Opening-Balances
2020-08-15 balance Assets:GBP:Current 1000.0 GBP
2020-08-16 custom "envelope" "allocate" "Expenses:Learning" 100.00


2020-08-20 * "Lesson"
  Assets:GBP:Current    -20.00 GBP
  Expenses:Learning     20.00 GBP
```

**Comment by JonBoyleCoding** [comment]
I've tried changing the pad to be a separate income rather than a pad and it still shows as the same.

**Comment by JonBoyleCoding** [comment]
This is the macro being called:

https://github.com/polarmutex/fava-envelope/blob/39cddee9fb87471cf451fda149f02d0ff00202b5/fava_envelope/templates/_budget_table.html#L42-L65

Based on the HTML source of the fava envelope page, it looks like Contents is being passed as something as it places this in the source:

https://github.com/polarmutex/fava-envelope/blob/39cddee9fb87471cf451fda149f02d0ff00202b5/fava_envelope/templates/_budget_table.html#L44


`<pre><code>[(&#39;Name&#39;, &#34;&lt;class &#39;str&#39;&gt;&#34;), (&#39;Amount&#39;, &#34;&lt;class &#39;decimal.Decimal&#39;&gt;&#34;)]</code></pre>`


It prints the contents if the contents is not none, I'm guessing, but as far as I can tell that shouldn't be possible as the only calls I can find to it are here as far as I can see:

https://github.com/polarmutex/fava-envelope/blob/39cddee9fb87471cf451fda149f02d0ff00202b5/fava_envelope/templates/EnvelopeBudget.html#L17-L21

**Comment by JonBoyleCoding** [comment]
Ok, I've determined that the query table being generated is not from the Line 44 as mentioned above, I modified the code to remove the if statement and it showed up the same, so I presume it's calling a different function somewhere.

**Comment by JonBoyleCoding** [comment]
I'm guessing it's got something to do with the querytable being updated in fava to have a different signature

https://github.com/beancount/fava/blob/be060267e119597b85d28065077b867360a8a543/src/fava/templates/_query_table.html#L50-L82

**Comment by JonBoyleCoding** [comment]
Ok yes, I've confirmed it's an issue between this and current version of fava on git. The pip package of fava doesn't have the issue.

I won't close the issue as this is probably something that needs to be updated at somepoint, although for the time being I can use fava-envelope on the pip releases.

**Comment by polarmutex** [comment]
i will take a look at this as soon as i can, thx for reporting

**Comment by polarmutex** [comment]
i am going to look into reworking this. I am probably using some private apis that I should not be using so future git changes should not break this plugin

**Comment by polarmutex** [comment]
with fava pushing release of this change, I am working on a fix.

**Comment by GuillaumedeVolpiano** [comment]
Anyway one can help?

**Comment by winduser** [comment]
Hello, it seems this bug still occurs to me. I've tried an example file and does not make the envelope budget correct. Is there anything I've done wrong?
<img width="1706" alt="CleanShot 2021-07-19 at 16 04 07@2x" src="https://user-images.githubusercontent.com/5322700/126125036-525191c3-5817-4e27-9f79-12d0a424f3e9.png">
[example.beancount.txt](https://github.com/polarmutex/fava-envelope/files/6839018/example.beancount.txt)

**Comment by polarmutex** [comment]
I will try to look into this when I get a chance, thx for reporting
