### ISSUE TITLE
Python 3.9 Upgrade Broke Plugin (FreeBSD 13.1)

### ISSUE THREAD

**Issue by bedwardly-down** [polarmutex/fava-envelope#51]
## What Happened
I upgraded my python version to the latest supported release for FreeBSD. The webpage is now showing just pure HTML and not rendering properly on any device.

![image](https://user-images.githubusercontent.com/59133880/177053317-2d344ab9-aba3-4271-b337-16462f9c647d.png)

## How to reproduce
1) Upgrade the python port to latest release
2) Remove the virtual env directory
3) Run `virtualenv env; . env/bin/activate`
4) `pip install git+https://github.com/polarmutex/fava-envelope.git`
5) Start fava

## Extra Details
I was perusing my stdout logs and noticed that this keeps appearing when restarting Fava:

`Jul  8 03:08:32 budget fava[79407]: Error in atexit._run_exitfuncs:
Jul  8 03:08:32 budget fava[79407]: Traceback (most recent call last):
Jul  8 03:08:32 budget fava[79407]:   File "/usr/home/fava/env/lib/python3.9/site-packages/beancount/query/shell.py", line 63, in save_history
Jul  8 03:08:32 budget fava[79407]:     readline.write_history_file(filename)
Jul  8 03:08:32 budget fava[79407]: PermissionError: [Errno 13] Permission denied`

It only started recently

**Comment by expired00** [comment]
This same behavior is occurring on the slim python docker images 3.7, 3.8, 3.9 and 3.10 (ex. python:3.7-slim)

**Comment by bedwardly-down** [comment]
What OS are you on, @expired00 ?

**Comment by expired00** [comment]
Debian Bullseye

**Comment by bedwardly-down** [comment]
I'm not sure what to try to get this working right now and not fully sure what broke it yet

**Comment by polarmutex** [comment]
Sorry I have not had any time to look at this, I will try to figure it out when I can

**Comment by bedwardly-down** [comment]
@expired00 have you upgraded numpy and protobuf to the latest versions yet? Asking because after upgrading both, I was able to get it to render properly again. I'm not sure what changed between releases

**Comment by polarmutex** [comment]
I can upgrade the poetry lock file if that is the issue

**Comment by JonBoyleCoding** [comment]
I am also having this issue, although I believe in my case it's related to the fava version. If I use fava 1.22 as installed via system packages, it displays the output above. If I run it with 1.21 as defined in the pyproject.toml it runs fine.

To note: I'm using python 3.10.5.
