### ISSUE TITLE
Importing module "fava_envelope" failed error

### ISSUE THREAD

**Issue by Mounica134** [polarmutex/fava-envelope#59]
Hello, I have been using fava-envelope v0.5.4 for 3-4 months now. I upgraded to v0.5.5 on my terminal while an instance of fava was accidentally running. Since then it throws an error that it can't load fava_envelope module even if I downgrade to v0.5.4. I'm not sure what broke and I don't know how to debug this. It's more a help plea than an issue. Sorry about that!

**Comment by polarmutex** [comment]
Sorry I was rushing a release since fava deprecated a api I was using. It worked for me pip installing the directory, but I did not test pypi. I will take a look at it today

**Comment by Mounica134** [comment]
You are right! I downgraded my fava to 1.22.3 and fava-envelope to 0.5.4 and it started working again. Thanks a lot!

**Comment by polarmutex** [comment]
push new update that works for me, let me know if you have any more issues

**Comment by vorburger** [comment]
see #64
