### ISSUE TITLE
Pandas not installed by default

### ISSUE THREAD

**Issue by BrendanKOz** [polarmutex/fava-envelope#64]
I just ran a release upgrade on the VM that fava is running on and had to reinstall my third-party plugins.

Fava-envelope was refusing load.
I tried running fava_envelope/main.py manually, and it errored out with a missing dependency for pandas.

pip install pandas

This causes pandas (and numpy) to install. Restarting fava has now cleared the error, and envelopes are back.

**Comment by vorburger** [comment]
Same here, and this combination "worked" (in quotes because seeing #67):

    pip3 install --upgrade beancount==2.3.5 fava==1.23.1 fava-envelope==0.5.6 pandas==1.5.2

@polarmutex I guess this means you should be adding pandas as a dependency?

**Comment by polarmutex** [comment]
should be fixed in 0.5.7
