### ISSUE TITLE
Importing module "fava_envelope" failed.  

### ISSUE THREAD

**Issue by kklod** [polarmutex/fava-envelope#66]
Got this error.  (fava version == 1.23)
![image](https://user-images.githubusercontent.com/50442661/209284919-8ec46296-cbe0-4ca3-ad9d-5141398be020.png)

**Comment by kklod** [comment]
more details: 
Upgrade fava to version 1.23.1, problem still exists! (OS: Debian)
But, when I ran fava(1.23.1)  on windows 10 , the extension work well!
-_-||

**Comment by polarmutex** [comment]
ok, will look into it

**Comment by kklod** [comment]
Well, found it the same problem as issue #64 

After “pip install pandas”， Problem Solved！
