### ISSUE TITLE
Latest version of pandas results in empty 'Available' column

### ISSUE THREAD

**Issue by wundor** [polarmutex/fava-envelope#72]
Hi.
I noticed that 'available' column on the 'envelope budget' page is completely empty when I use `pandas==2.0.0` and above. Seems like some [incompatible changes](https://pandas.pydata.org/docs/whatsnew/v2.0.0.html) were made when v2 got released. For now I was able to get it to work by pinning `pandas` to the latest v1 version

```bash
pip install --upgrade beancount fava fava-envelope pandas==1.5.3
```

I'm using Python 3.11.3 on Arch. I will try to take a look, but I suck at pandas (and python overall)

**Comment by polarmutex** [comment]
should be fixed in 0.5.8
